name: vird
description: A calming, spiritually immersive Islamic Vird app

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0
  # UI & Animation
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9

  # Storage & Database
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3

  # Audio & Media
  audioplayers: ^5.2.1
  flutter_tts: ^3.8.3

  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # Backend Integration
  supabase_flutter: ^2.0.0
  http: ^1.1.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Utilities
  uuid: ^4.2.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0
  timeago: ^3.6.0
  # Arabic/Islamic Features
  hijri: ^3.0.0
  adhan: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/vird_logo.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true

  assets:
#    - assets/images/
#    - assets/audio/
#    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade-Regular.ttf
        - asset: assets/fonts/Scheherazade-Bold.ttf
          weight: 700