import '../../models/surah.dart';

class SurahYaseenComplete {
  static Surah getSurah() {
    return Surah(
      number: 36,
      arabicName: 'سُورَةُ يٰسٓ',
      englishName: 'Yaseen',
      transliteration: 'Ya-Seen',
      verses: 83,
      revelation: 'Meccan',
      meaning: 'Ya-Seen (Arabic Letters)',
      benefits: [
        'Heart of the Quran',
        'Brings ease for the day when read in morning',
        'Forgiveness of sins',
        'Intercession on Day of Judgment',
        'Spiritual purification'
      ],
      recommendedTimes: ['morning', 'friday'],
      audioUrl: 'https://example.com/audio/036.mp3',
      fullText: [
        Verse(
          number: 1,
          arabic: 'يٰسٓ',
          translation: 'Ya, Seen.',
          transliteration: 'Ya-Seen',
        ),
        Verse(
          number: 2,
          arabic: 'وَالْقُرْآنِ الْحَكِيمِ',
          translation: 'By the wise Qur\'an.',
          transliteration: 'Wal-Qur\'anil-hakeem',
        ),
        Verse(
          number: 3,
          arabic: 'إِنَّكَ لَمِنَ الْمُرْسَلِينَ',
          translation: 'Indeed you, [O Muhammad], are from among the messengers,',
          transliteration: 'Innaka laminal-mursaleen',
        ),
        Verse(
          number: 4,
          arabic: 'عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ',
          translation: 'On a straight path.',
          transliteration: 'Ala siratin mustaqeem',
        ),
        Verse(
          number: 5,
          arabic: 'تَنزِيلَ الْعَزِيزِ الرَّحِيمِ',
          translation: '[This is] a revelation of the Exalted in Might, the Merciful,',
          transliteration: 'Tanzeelal-azeezir-raheem',
        ),
        Verse(
          number: 6,
          arabic: 'لِتُنذِرَ قَوْمًا مَّا أُنذِرَ آبَاؤُهُمْ فَهُمْ غَافِلُونَ',
          translation: 'That you may warn a people whose forefathers were not warned, so they are unaware.',
          transliteration: 'Litunzira qawman ma unzira abauhum fahum ghafiloon',
        ),
        Verse(
          number: 7,
          arabic: 'لَقَدْ حَقَّ الْقَوْلُ عَلَىٰ أَكْثَرِهِمْ فَهُمْ لَا يُؤْمِنُونَ',
          translation: 'Already the word has come into effect upon most of them, so they do not believe.',
          transliteration: 'Laqad haqqal-qawlu ala aktharihim fahum la yu\'minoon',
        ),
        Verse(
          number: 8,
          arabic: 'إِنَّا جَعَلْنَا فِي أَعْنَاقِهِمْ أَغْلَالًا فَهِيَ إِلَى الْأَذْقَانِ فَهُم مُّقْمَحُونَ',
          translation: 'Indeed, We have put shackles on their necks, and they are to their chins, so they are with heads [kept] aloft.',
          transliteration: 'Inna ja\'alna fee a\'naqihim aghlalan fahiya ilal-azqani fahum muqmahoon',
        ),
        Verse(
          number: 9,
          arabic: 'وَجَعَلْنَا مِن بَيْنِ أَيْدِيهِمْ سَدًّا وَمِنْ خَلْفِهِمْ سَدًّا فَأَغْشَيْنَاهُمْ فَهُمْ لَا يُبْصِرُونَ',
          translation: 'And We have put before them a barrier and behind them a barrier and covered them, so they do not see.',
          transliteration: 'Wa ja\'alna min bayni aydeehim saddan wa min khalfihim saddan fa-aghshaynahum fahum la yubsiroon',
        ),
        Verse(
          number: 10,
          arabic: 'وَسَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ',
          translation: 'And it is all the same for them whether you warn them or do not warn them - they will not believe.',
          transliteration: 'Wa sawaun alayhim a-anzartahum am lam tunzirhum la yu\'minoon',
        ),
        Verse(
          number: 11,
          arabic: 'إِنَّمَا تُنذِرُ مَنِ اتَّبَعَ الذِّكْرَ وَخَشِيَ الرَّحْمَٰنَ بِالْغَيْبِ ۖ فَبَشِّرْهُ بِمَغْفِرَةٍ وَأَجْرٍ كَرِيمٍ',
          translation: 'You can only warn one who follows the message and fears the Most Merciful unseen. So give him good tidings of forgiveness and noble reward.',
          transliteration: 'Innama tunziru manittaba\'az-zikra wa khashiyar-rahmana bilghayb fa-bashshirhu bimaghfiratin wa ajrin kareem',
        ),
        Verse(
          number: 12,
          arabic: 'إِنَّا نَحْنُ نُحْيِي الْمَوْتَىٰ وَنَكْتُبُ مَا قَدَّمُوا وَآثَارَهُمْ ۚ وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ فِي إِمَامٍ مُّبِينٍ',
          translation: 'Indeed, it is We who bring the dead to life and record what they have put forth and what they have left behind, and all things We have enumerated in a clear register.',
          transliteration: 'Inna nahnu nuhyil-mawta wa naktubu ma qaddamu wa atharahum wa kulla shay\'in ahsaynahu fee imamin mubeen',
        ),
        Verse(
          number: 13,
          arabic: 'وَاضْرِبْ لَهُم مَّثَلًا أَصْحَابَ الْقَرْيَةِ إِذْ جَاءَهَا الْمُرْسَلُونَ',
          translation: 'And present to them an example: the people of the city, when the messengers came to it -',
          transliteration: 'Wadrib lahum mathalan as-habal-qaryati iz ja\'ahal-mursaloon',
        ),
        Verse(
          number: 14,
          arabic: 'إِذْ أَرْسَلْنَا إِلَيْهِمُ اثْنَيْنِ فَكَذَّبُوهُمَا فَعَزَّزْنَا بِثَالِثٍ فَقَالُوا إِنَّا إِلَيْكُم مُّرْسَلُونَ',
          translation: 'When We sent to them two but they denied them, so We strengthened them with a third, and they said, "Indeed, we are messengers to you."',
          transliteration: 'Iz arsalna ilayhimus-nayni fakazaboohuma fa\'azzazna bithalithin faqaloo inna ilaykum mursaloon',
        ),
        Verse(
          number: 15,
          arabic: 'قَالُوا مَا أَنتُمْ إِلَّا بَشَرٌ مِّثْلُنَا وَمَا أَنزَلَ الرَّحْمَٰنُ مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا تَكْذِبُونَ',
          translation: 'They said, "You are not but human beings like us, and the Most Merciful has not revealed a thing. You are only telling lies."',
          transliteration: 'Qaloo ma antum illa basharum mithluna wa ma anzalar-rahmanu min shay\'in in antum illa takziboon',
        ),
        Verse(
          number: 16,
          arabic: 'قَالُوا رَبُّنَا يَعْلَمُ إِنَّا إِلَيْكُمْ لَمُرْسَلُونَ',
          translation: 'They said, "Our Lord knows that we are messengers to you,',
          transliteration: 'Qaloo rabbuna ya\'lamu inna ilaykum lamursaloon',
        ),
        Verse(
          number: 17,
          arabic: 'وَمَا عَلَيْنَا إِلَّا الْبَلَاغُ الْمُبِينُ',
          translation: 'And we are not responsible except for clear notification."',
          transliteration: 'Wa ma alayna illal-balaghul-mubeen',
        ),
        Verse(
          number: 18,
          arabic: 'قَالُوا إِنَّا تَطَيَّرْنَا بِكُمْ ۖ لَئِن لَّمْ تَنتَهُوا لَنَرْجُمَنَّكُمْ وَلَيَمَسَّنَّكُم مِّنَّا عَذَابٌ أَلِيمٌ',
          translation: 'They said, "Indeed, we consider you a bad omen. If you do not desist, we will surely stone you, and there will surely touch you, from us, a painful punishment."',
          transliteration: 'Qaloo inna tatayyarna bikum la\'il-lam tantahoo lanarjumannakum wa layamassannakum minna azabun aleem',
        ),
        Verse(
          number: 19,
          arabic: 'قَالُوا طَائِرُكُم مَّعَكُمْ ۚ أَئِن ذُكِّرْتُم ۚ بَلْ أَنتُمْ قَوْمٌ مُّسْرِفُونَ',
          translation: 'They said, "Your omen is with yourselves. Is it because you were reminded? Rather, you are a transgressing people."',
          transliteration: 'Qaloo ta-irukum ma\'akum a\'in zukkirtum bal antum qawmum musrifoon',
        ),
        Verse(
          number: 20,
          arabic: 'وَجَاءَ مِنْ أَقْصَى الْمَدِينَةِ رَجُلٌ يَسْعَىٰ قَالَ يَا قَوْمِ اتَّبِعُوا الْمُرْسَلِينَ',
          translation: 'And there came from the farthest end of the city a man, running. He said, "O my people, follow the messengers.',
          transliteration: 'Wa ja\'a min aqsal-madinati rajulun yas\'a qala ya qawmit-tabi\'ul-mursaleen',
        ),
        Verse(
          number: 21,
          arabic: 'اتَّبِعُوا مَن لَّا يَسْأَلُكُمْ أَجْرًا وَهُم مُّهْتَدُونَ',
          translation: 'Follow those who do not ask of you [any] payment, and they are [rightly] guided.',
          transliteration: 'Ittabi\'oo mal-la yas\'alukum ajranw-wa hum muhtadoon',
        ),
        Verse(
          number: 22,
          arabic: 'وَمَا لِيَ لَا أَعْبُدُ الَّذِي فَطَرَنِي وَإِلَيْهِ تُرْجَعُونَ',
          translation: 'And why should I not worship He who created me and to whom you will be returned?',
          transliteration: 'Wa ma liya la a\'budul-lazee fataranee wa ilayhi turja\'oon',
        ),
        Verse(
          number: 23,
          arabic: 'أَأَتَّخِذُ مِن دُونِهِ آلِهَةً إِن يُرِدْنِ الرَّحْمَٰنُ بِضُرٍّ لَّا تُغْنِ عَنِّي شَفَاعَتُهُمْ شَيْئًا وَلَا يُنقِذُونِ',
          translation: 'Should I take other than Him [false] deities [while], if the Most Merciful intends for me some adversity, their intercession will not avail me at all, nor can they save me?',
          transliteration: 'A-attakhizu min doonihi alihatan iny-yuridnir-rahmanu bidurril-la tughni \'annee shafa\'atuhum shay\'anw-wa la yunqizoon',
        ),
        Verse(
          number: 24,
          arabic: 'إِنِّي إِذًا لَّفِي ضَلَالٍ مُّبِينٍ',
          translation: 'Indeed, I would then be in manifest error.',
          transliteration: 'Innee izal-lafee dalalin mubeen',
        ),
        Verse(
          number: 25,
          arabic: 'إِنِّي آمَنتُ بِرَبِّكُمْ فَاسْمَعُونِ',
          translation: 'Indeed, I have believed in your Lord, so listen to me.',
          transliteration: 'Innee amantu bi-rabbikum fasma\'oon',
        ),
        Verse(
          number: 26,
          arabic: 'قِيلَ ادْخُلِ الْجَنَّةَ ۖ قَالَ يَا لَيْتَ قَوْمِي يَعْلَمُونَ',
          translation: 'It was said, "Enter Paradise." He said, "I wish my people could know',
          transliteration: 'Qeelad-khulil-jannah; qala ya layta qawmee ya\'lamoon',
        ),
        Verse(
          number: 27,
          arabic: 'بِمَا غَفَرَ لِي رَبِّي وَجَعَلَنِي مِنَ الْمُكْرَمِينَ',
          translation: 'Of how my Lord has forgiven me and placed me among the honored."',
          transliteration: 'Bima ghafara lee rabbee wa ja\'alanee minal-mukrameen',
        ),
        Verse(
          number: 28,
          arabic: 'وَمَا أَنزَلْنَا عَلَىٰ قَوْمِهِ مِن بَعْدِهِ مِن جُندٍ مِّنَ السَّمَاءِ وَمَا كُنَّا مُنزِلِينَ',
          translation: 'And We did not send down upon his people after him any soldiers from the heaven, nor would We have done so.',
          transliteration: 'Wa ma anzalna ala qawmihi mim ba\'dihi min jundim minas-sama\'i wa ma kunna munzileen',
        ),
        Verse(
          number: 29,
          arabic: 'إِن كَانَتْ إِلَّا صَيْحَةً وَاحِدَةً فَإِذَا هُمْ خَامِدُونَ',
          translation: 'It was not but one shout, and immediately they were extinguished.',
          transliteration: 'In kanat illa sayhatan wahidatan fa-iza hum khamidoon',
        ),
        Verse(
          number: 30,
          arabic: 'يَا حَسْرَةً عَلَى الْعِبَادِ ۚ مَا يَأْتِيهِم مِّن رَّسُولٍ إِلَّا كَانُوا بِهِ يَسْتَهْزِئُونَ',
          translation: 'How regretful for the servants. There did not come to them any messenger except that they used to ridicule him.',
          transliteration: 'Ya hasratan \'alal-\'ibad; ma ya\'teehim mir-rasoolin illa kanoo bihee yastahzi\'oon',
        ),
        Verse(
          number: 31,
          arabic: 'أَلَمْ يَرَوْا كَمْ أَهْلَكْنَا قَبْلَهُم مِّنَ الْقُرُونِ أَنَّهُمْ إِلَيْهِمْ لَا يَرْجِعُونَ',
          translation: 'Have they not considered how many generations We destroyed before them - that they to them will not return?',
          transliteration: 'Alam yaraw kam ahlakna qablahum minal-qurooni annahum ilayhim la yarji\'oon',
        ),
        Verse(
          number: 32,
          arabic: 'وَإِن كُلٌّ لَّمَّا جَمِيعٌ لَّدَيْنَا مُحْضَرُونَ',
          translation: 'And indeed, all of them will yet be brought present before Us.',
          transliteration: 'Wa in kullul-lamma jamee\'ul-ladayna muhdaroon',
        ),
        Verse(
          number: 33,
          arabic: 'وَآيَةٌ لَّهُمُ الْأَرْضُ الْمَيْتَةُ أَحْيَيْنَاهَا وَأَخْرَجْنَا مِنْهَا حَبًّا فَمِنْهُ يَأْكُلُونَ',
          translation: 'And a sign for them is the dead earth. We have brought it to life and brought forth from it grain, and from it they eat.',
          transliteration: 'Wa ayatul-lahumul-ardul-maytatu ahyaynaha wa akhrajna minha habban faminhu ya\'kuloon',
        ),
        Verse(
          number: 34,
          arabic: 'وَجَعَلْنَا فِيهَا جَنَّاتٍ مِّن نَّخِيلٍ وَأَعْنَابٍ وَفَجَّرْنَا فِيهَا مِنَ الْعُيُونِ',
          translation: 'And We placed therein gardens of palm trees and grapevines and caused to burst forth therefrom some springs -',
          transliteration: 'Wa ja\'alna feeha jannatin min nakheelinw-wa a\'nabin wa fajjarna feeha minal-\'uyoon',
        ),
        Verse(
          number: 35,
          arabic: 'لِيَأْكُلُوا مِن ثَمَرِهِ وَمَا عَمِلَتْهُ أَيْدِيهِمْ ۖ أَفَلَا يَشْكُرُونَ',
          translation: 'That they may eat of His fruit. And their hands have not produced it, so will they not be grateful?',
          transliteration: 'Liya\'kuloo min samarihee wa ma \'amilat-hu aydeehim; afala yashkuroon',
        ),
        Verse(
          number: 36,
          arabic: 'سُبْحَانَ الَّذِي خَلَقَ الْأَزْوَاجَ كُلَّهَا مِمَّا تُنبِتُ الْأَرْضُ وَمِنْ أَنفُسِهِمْ وَمِمَّا لَا يَعْلَمُونَ',
          translation: 'Exalted is He who created all pairs - from what the earth grows and from themselves and from that which they do not know.',
          transliteration: 'Subhanal-lazee khalaqal-azwaja kullaha mimma tunbitul-ardu wa min anfusihim wa mimma la ya\'lamoon',
        ),
        Verse(
          number: 37,
          arabic: 'وَآيَةٌ لَّهُمُ اللَّيْلُ نَسْلَخُ مِنْهُ النَّهَارَ فَإِذَا هُم مُّظْلِمُونَ',
          translation: 'And a sign for them is the night. We remove from it [the light of] day, so they are [left] in darkness.',
          transliteration: 'Wa ayatul-lahumul-laylu naslakhu minhun-nahara fa-iza hum muzlimoon',
        ),
        Verse(
          number: 38,
          arabic: 'وَالشَّمْسُ تَجْرِي لِمُسْتَقَرٍّ لَّهَا ۚ ذَٰلِكَ تَقْدِيرُ الْعَزِيزِ الْعَلِيمِ',
          translation: 'And the sun runs [on course] toward its stopping point. That is the determination of the Exalted in Might, the Knowing.',
          transliteration: 'Wash-shamsu tajree limustaqarril-laha; zalika taqdeerul-\'azeezil-\'aleem',
        ),
        Verse(
          number: 39,
          arabic: 'وَالْقَمَرَ قَدَّرْنَاهُ مَنَازِلَ حَتَّىٰ عَادَ كَالْعُرْجُونِ الْقَدِيمِ',
          translation: 'And the moon - We have determined for it phases, until it returns [appearing] like the old date stalk.',
          transliteration: 'Wal-qamara qaddarnahu manazila hatta \'ada kal-\'urjoonil-qadeem',
        ),
        Verse(
          number: 40,
          arabic: 'لَا الشَّمْسُ يَنبَغِي لَهَا أَن تُدْرِكَ الْقَمَرَ وَلَا اللَّيْلُ سَابِقُ النَّهَارِ ۚ وَكُلٌّ فِي فَلَكٍ يَسْبَحُونَ',
          translation: 'It is not allowable for the sun to reach the moon, nor does the night overtake the day, but each, in an orbit, is swimming.',
          transliteration: 'Lash-shamsu yanbaghee laha an tudrikal-qamara wa lal-laylu sabiqun-nahar; wa kullun fee falakin yasbahoon',
        ),
        Verse(
          number: 41,
          arabic: 'وَآيَةٌ لَّهُمْ أَنَّا حَمَلْنَا ذُرِّيَّتَهُمْ فِي الْفُلْكِ الْمَشْحُونِ',
          translation: 'And a sign for them is that We carried their forefathers in a laden ship.',
          transliteration: 'Wa ayatul-lahum anna hamalna zurriyyatahum fil-fulkil-mashhood',
        ),
        Verse(
          number: 42,
          arabic: 'وَخَلَقْنَا لَهُم مِّن مِّثْلِهِ مَا يَرْكَبُونَ',
          translation: 'And We created for them from the like of it that which they ride.',
          transliteration: 'Wa khalaqna lahum mim mislihee ma yarkaboon',
        ),
        Verse(
          number: 43,
          arabic: 'وَإِن نَّشَأْ نُغْرِقْهُمْ فَلَا صَرِيخَ لَهُمْ وَلَا هُمْ يُنقَذُونَ',
          translation: 'And if We should will, We could drown them; then no one responding to a cry would there be for them, nor would they be saved',
          transliteration: 'Wa in nasha\' nughriqhum fala sareekha lahum wa la hum yunqazoon',
        ),
        Verse(
          number: 44,
          arabic: 'إِلَّا رَحْمَةً مِّنَّا وَمَتَاعًا إِلَىٰ حِينٍ',
          translation: 'Except as a mercy from Us and provision for a time.',
          transliteration: 'Illa rahmatan minna wa mata\'an ila heen',
        ),
        Verse(
          number: 45,
          arabic: 'وَإِذَا قِيلَ لَهُمُ اتَّقُوا مَا بَيْنَ أَيْدِيكُمْ وَمَا خَلْفَكُمْ لَعَلَّكُمْ تُرْحَمُونَ',
          translation: 'But when it is said to them, "Beware of what is before you and what is behind you; perhaps you will receive mercy..."',
          transliteration: 'Wa iza qeela lahumut-taqoo ma bayna aydeekum wa ma khalfakum la\'allakum turhamoon',
        ),
        Verse(
          number: 46,
          arabic: 'وَمَا تَأْتِيهِم مِّنْ آيَةٍ مِّنْ آيَاتِ رَبِّهِمْ إِلَّا كَانُوا عَنْهَا مُعْرِضِينَ',
          translation: 'And no sign comes to them from the signs of their Lord except that they are from it turning away.',
          transliteration: 'Wa ma ta\'teehim min ayatim min ayati rabbihim illa kanoo \'anha mu\'rideen',
        ),
        Verse(
          number: 47,
          arabic: 'وَإِذَا قِيلَ لَهُمْ أَنفِقُوا مِمَّا رَزَقَكُمُ اللَّهُ قَالَ الَّذِينَ كَفَرُوا لِلَّذِينَ آمَنُوا أَنُطْعِمُ مَن لَّوْ يَشَاءُ اللَّهُ أَطْعَمَهُ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ مُّبِينٍ',
          translation: 'And when it is said to them, "Spend from that which Allah has provided for you," those who disbelieve say to those who believe, "Should we feed one whom, if Allah had willed, He would have fed? You are not but in clear error."',
          transliteration: 'Wa iza qeela lahum anfiqoo mimma razaqakumul-lahu qalal-lazeena kafaroo lillazeena amanoo anut\'imu mal-law yashaul-lahu at\'amah; in antum illa fee dalalin mubeen',
        ),
        Verse(
          number: 48,
          arabic: 'وَيَقُولُونَ مَتَىٰ هَٰذَا الْوَعْدُ إِن كُنتُمْ صَادِقِينَ',
          translation: 'And they say, "When is this promise, if you should be truthful?"',
          transliteration: 'Wa yaqooloona mata hazal-wa\'du in kuntum sadiqeen',
        ),
        Verse(
          number: 49,
          arabic: 'مَا يَنظُرُونَ إِلَّا صَيْحَةً وَاحِدَةً تَأْخُذُهُمْ وَهُمْ يَخِصِّمُونَ',
          translation: 'They do not await except one blast which will seize them while they are disputing.',
          transliteration: 'Ma yanzuroona illa sayhatan wahidatan ta\'khuzuhum wa hum yakhissimoon',
        ),
        Verse(
          number: 50,
          arabic: 'فَلَا يَسْتَطِيعُونَ تَوْصِيَةً وَلَا إِلَىٰ أَهْلِهِمْ يَرْجِعُونَ',
          translation: 'And they will not be able [to give] any instruction, nor to their people can they return.',
          transliteration: 'Fala yastatee\'oona tawsiyatan wa la ila ahlihim yarji\'oon',
        ),
        Verse(
          number: 51,
          arabic: 'وَنُفِخَ فِي الصُّورِ فَإِذَا هُم مِّنَ الْأَجْدَاثِ إِلَىٰ رَبِّهِمْ يَنسِلُونَ',
          translation: 'And the Horn will be blown; and at once from the graves to their Lord they will hasten.',
          transliteration: 'Wa nufikha fis-soori fa-iza hum minal-ajdasi ila rabbihim yansiloon',
        ),
        Verse(
          number: 52,
          arabic: 'قَالُوا يَا وَيْلَنَا مَن بَعَثَنَا مِن مَّرْقَدِنَا ۜ ۗ هَٰذَا مَا وَعَدَ الرَّحْمَٰنُ وَصَدَقَ الْمُرْسَلُونَ',
          translation: 'They will say, "O woe to us! Who has raised us up from our sleeping place?" [The reply will be], "This is what the Most Merciful had promised, and the messengers spoke the truth."',
          transliteration: 'Qaloo ya waylana mam ba\'asana mim marqadina; haza ma wa\'adar-rahmanu wa sadaqal-mursaloon',
        ),
        Verse(
          number: 53,
          arabic: 'إِن كَانَتْ إِلَّا صَيْحَةً وَاحِدَةً فَإِذَا هُمْ جَمِيعٌ لَّدَيْنَا مُحْضَرُونَ',
          translation: 'It will not be but one blast, and at once they are all brought present before Us.',
          transliteration: 'In kanat illa sayhatan wahidatan fa-iza hum jamee\'ul-ladayna muhdaroon',
        ),
        Verse(
          number: 54,
          arabic: 'فَالْيَوْمَ لَا تُظْلَمُ نَفْسٌ شَيْئًا وَلَا تُجْزَوْنَ إِلَّا مَا كُنتُمْ تَعْمَلُونَ',
          translation: 'So today no soul will be wronged at all, and you will not be recompensed except for what you used to do.',
          transliteration: 'Fal-yawma la tuzlamu nafsun shay\'an wa la tujzawna illa ma kuntum ta\'maloon',
        ),
        Verse(
          number: 55,
          arabic: 'إِنَّ أَصْحَابَ الْجَنَّةِ الْيَوْمَ فِي شُغُلٍ فَاكِهُونَ',
          translation: 'Indeed the companions of Paradise, that Day, will be amused in [joyful] occupation -',
          transliteration: 'Inna as-habal-jannatil-yawma fee shughulin fakihoon',
        ),
        Verse(
          number: 56,
          arabic: 'هُمْ وَأَزْوَاجُهُمْ فِي ظِلَالٍ عَلَى الْأَرَائِكِ مُتَّكِئُونَ',
          translation: 'They and their spouses - in shade, reclining on adorned couches.',
          transliteration: 'Hum wa azwajuhum fee zilalin \'alal-ara\'iki muttaki\'oon',
        ),
        Verse(
          number: 57,
          arabic: 'لَهُمْ فِيهَا فَاكِهَةٌ وَلَهُم مَّا يَدَّعُونَ',
          translation: 'For them therein is fruit, and for them is whatever they request [or wish]',
          transliteration: 'Lahum feeha fakihatun wa lahum ma yadda\'oon',
        ),
        Verse(
          number: 58,
          arabic: 'سَلَامٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ',
          translation: '"Peace," a word from a Merciful Lord.',
          transliteration: 'Salamun qawlam mir-rabbin raheem',
        ),
        Verse(
          number: 59,
          arabic: 'وَامْتَازُوا الْيَوْمَ أَيُّهَا الْمُجْرِمُونَ',
          translation: 'But stand apart today, you criminals.',
          transliteration: 'Wamtazul-yawma ayyuhal-mujrimoon',
        ),
        Verse(
          number: 60,
          arabic: 'أَلَمْ أَعْهَدْ إِلَيْكُمْ يَا بَنِي آدَمَ أَن لَّا تَعْبُدُوا الشَّيْطَانَ ۖ إِنَّهُ لَكُمْ عَدُوٌّ مُّبِينٌ',
          translation: 'Did I not enjoin upon you, O children of Adam, that you not worship Satan - [for] indeed, he is to you a clear enemy -',
          transliteration: 'Alam a\'had ilaykum ya banee adama al-la ta\'budush-shaytana innahu lakum \'aduwwum mubeen',
        ),
        Verse(
          number: 61,
          arabic: 'وَأَنِ اعْبُدُونِي ۚ هَٰذَا صِرَاطٌ مُّسْتَقِيمٌ',
          translation: 'And that you worship [only] Me? This is a straight path.',
          transliteration: 'Wa ani\'budoonee haza siratun mustaqeem',
        ),
        Verse(
          number: 62,
          arabic: 'وَلَقَدْ أَضَلَّ مِنكُمْ جِبِلًّا كَثِيرًا ۖ أَفَلَمْ تَكُونُوا تَعْقِلُونَ',
          translation: 'And he had already led astray from among you much of creation, so did you not use reason?',
          transliteration: 'Wa laqad adalla minkum jibillan kaseera; afalam takoonoo ta\'qiloon',
        ),
        Verse(
          number: 63,
          arabic: 'هَٰذِهِ جَهَنَّمُ الَّتِي كُنتُمْ تُوعَدُونَ',
          translation: 'This is the Hellfire which you were promised.',
          transliteration: 'Hazihee jahannamul-latee kuntum too\'adoon',
        ),
        Verse(
          number: 64,
          arabic: 'اصْلَوْهَا الْيَوْمَ بِمَا كُنتُمْ تَكْفُرُونَ',
          translation: 'Enter to burn therein today for what you used to deny.',
          transliteration: 'Islawhal-yawma bima kuntum takfuroon',
        ),
        Verse(
          number: 65,
          arabic: 'الْيَوْمَ نَخْتِمُ عَلَىٰ أَفْوَاهِهِمْ وَتُكَلِّمُنَا أَيْدِيهِمْ وَتَشْهَدُ أَرْجُلُهُم بِمَا كَانُوا يَكْسِبُونَ',
          translation: 'That Day, We will seal over their mouths, and their hands will speak to Us, and their feet will testify about what they used to earn.',
          transliteration: 'Al-yawma nakhtimu ala afwahihim wa tukallimuna aydeehim wa tashhadu arjuluhum bima kanoo yaksiboon',
        ),
        Verse(
          number: 66,
          arabic: 'وَلَوْ نَشَاءُ لَطَمَسْنَا عَلَىٰ أَعْيُنِهِمْ فَاسْتَبَقُوا الصِّرَاطَ فَأَنَّىٰ يُبْصِرُونَ',
          translation: 'And if We willed, We could have obliterated their eyes, and they would race to [find] the path, and how could they see?',
          transliteration: 'Wa law nasha\'u latamasna ala a\'yunihim fastabaqus-sirata fa-anna yubsiroon',
        ),
        Verse(
          number: 67,
          arabic: 'وَلَوْ نَشَاءُ لَمَسَخْنَاهُمْ عَلَىٰ مَكَانَتِهِمْ فَمَا اسْتَطَاعُوا مُضِيًّا وَلَا يَرْجِعُونَ',
          translation: 'And if We willed, We could have deformed them, [paralyzing them] in their places so they would not be able to proceed, nor could they return [to their homes].',
          transliteration: 'Wa law nasha\'u lamasakhnahum ala makanatihim famas-tata\'oo mudiyyan wa la yarji\'oon',
        ),
        Verse(
          number: 68,
          arabic: 'وَمَن نُّعَمِّرْهُ نُنَكِّسْهُ فِي الْخَلْقِ ۖ أَفَلَا يَعْقِلُونَ',
          translation: 'And he to whom We grant long life We reverse in creation; so will they not understand?',
          transliteration: 'Wa man nu\'ammirhu nunakkishu fil-khalq; afala ya\'qiloon',
        ),
        Verse(
          number: 69,
          arabic: 'وَمَا عَلَّمْنَاهُ الشِّعْرَ وَمَا يَنبَغِي لَهُ ۚ إِنْ هُوَ إِلَّا ذِكْرٌ وَقُرْآنٌ مُّبِينٌ',
          translation: 'And We did not give Prophet Muhammad, knowledge of poetry, nor is it befitting for him. It is not but a message and a clear Qur\'an',
          transliteration: 'Wa ma \'allamnahush-shi\'ra wa ma yanbaghee lah; in huwa illa zikrun wa qur\'anum mubeen',
        ),
        Verse(
          number: 70,
          arabic: 'لِّيُنذِرَ مَن كَانَ حَيًّا وَيَحِقَّ الْقَوْلُ عَلَى الْكَافِرِينَ',
          translation: 'To warn whoever is alive and justify the word against the disbelievers.',
          transliteration: 'Liyunzira man kana hayyan wa yahiqqal-qawlu \'alal-kafireen',
        ),
        Verse(
          number: 71,
          arabic: 'أَوَلَمْ يَرَوْا أَنَّا خَلَقْنَا لَهُم مِّمَّا عَمِلَتْ أَيْدِينَا أَنْعَامًا فَهُمْ لَهَا مَالِكُونَ',
          translation: 'Do they not see that We have created for them from what Our hands have made, grazing livestock, and [then] they are their owners?',
          transliteration: 'Awalam yaraw anna khalaqna lahum mimma \'amilat aydeena an\'aman fahum laha malikoon',
        ),
        Verse(
          number: 72,
          arabic: 'وَذَلَّلْنَاهَا لَهُمْ فَمِنْهَا رَكُوبُهُمْ وَمِنْهَا يَأْكُلُونَ',
          translation: 'And We have tamed them for them, so some of them they ride, and some of them they eat.',
          transliteration: 'Wa zallalanaha lahum faminha rakoobuhum wa minha ya\'kuloon',
        ),
        Verse(
          number: 73,
          arabic: 'وَلَهُمْ فِيهَا مَنَافِعُ وَمَشَارِبُ ۖ أَفَلَا يَشْكُرُونَ',
          translation: 'And for them therein are [other] benefits and drinks, so will they not be grateful?',
          transliteration: 'Wa lahum feeha manafi\'u wa masharibu afala yashkuroon',
        ),
        Verse(
          number: 74,
          arabic: 'وَاتَّخَذُوا مِن دُونِ اللَّهِ آلِهَةً لَّعَلَّهُمْ يُنصَرُونَ',
          translation: 'But they have taken besides Allah [false] deities that perhaps they would be helped.',
          transliteration: 'Wattakhazoo min doonil-lahi alihatan la\'allahum yunsaroon',
        ),
        Verse(
          number: 75,
          arabic: 'لَا يَسْتَطِيعُونَ نَصْرَهُمْ وَهُمْ لَهُمْ جُندٌ مُّحْضَرُونَ',
          translation: 'They are not able to help them, and they [themselves] are for them soldiers in attendance.',
          transliteration: 'La yastatee\'oona nasrahum wa hum lahum jundum muhdaroon',
        ),
        Verse(
          number: 76,
          arabic: 'فَلَا يَحْزُنكَ قَوْلُهُمْ ۘ إِنَّا نَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ',
          translation: 'So let not their speech grieve you. Indeed, We know what they conceal and what they declare.',
          transliteration: 'Fala yahzunka qawluhum; inna na\'lamu ma yusirroona wa ma yu\'linoon',
        ),
        Verse(
          number: 77,
          arabic: 'أَوَلَمْ يَرَ الْإِنسَانُ أَنَّا خَلَقْنَاهُ مِن نُّطْفَةٍ فَإِذَا هُوَ خَصِيمٌ مُّبِينٌ',
          translation: 'Does man not consider that We created him from a [mere] sperm-drop - then at once he is a clear adversary?',
          transliteration: 'Awalam yaral-insanu anna khalaqnahu min nutfatin fa-iza huwa khaseemum mubeen',
        ),
        Verse(
          number: 78,
          arabic: 'وَضَرَبَ لَنَا مَثَلًا وَنَسِيَ خَلْقَهُ ۖ قَالَ مَن يُحْيِي الْعِظَامَ وَهِيَ رَمِيمٌ',
          translation: 'And he presents for Us an example and forgets his [own] creation. He says, "Who will give life to bones while they are disintegrated?"',
          transliteration: 'Wa daraba lana masalan wa nasiya khalqah; qala may-yuhyil-\'izama wa hiya rameem',
        ),
        Verse(
          number: 79,
          arabic: 'قُلْ يُحْيِيهَا الَّذِي أَنشَأَهَا أَوَّلَ مَرَّةٍ ۖ وَهُوَ بِكُلِّ خَلْقٍ عَلِيمٌ',
          translation: 'Say, "He will give them life who produced them the first time; and He is, of all creation, Knowing."',
          transliteration: 'Qul yuhyeehal-lazee ansa-aha awwala marrah; wa huwa bikulli khalqin \'aleem',
        ),
        Verse(
          number: 80,
          arabic: 'الَّذِي جَعَلَ لَكُم مِّنَ الشَّجَرِ الْأَخْضَرِ نَارًا فَإِذَا أَنتُم مِّنْهُ تُوقِدُونَ',
          translation: '[It is] He who made for you from the green tree, fire, and then from it you ignite.',
          transliteration: 'Allazee ja\'ala lakum minash-shajaril-akhdari naran fa-iza antum minhu tooqidoon',
        ),
        Verse(
          number: 81,
          arabic: 'أَوَلَيْسَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِقَادِرٍ عَلَىٰ أَن يَخْلُقَ مِثْلَهُم ۚ بَلَىٰ وَهُوَ الْخَلَّاقُ الْعَلِيمُ',
          translation: 'Is not He who created the heavens and the earth Able to create the likes of them? Yes, [it is so]; and He is the Knowing Creator.',
          transliteration: 'Awalaysal-lazee khalaqas-samawati wal-arda biqadirin ala ay-yakhluqa mislahum; bala wa huwal-khallaqul-\'aleem',
        ),
        Verse(
          number: 82,
          arabic: 'إِنَّمَا أَمْرُهُ إِذَا أَرَادَ شَيْئًا أَن يَقُولَ لَهُ كُن فَيَكُونُ',
          translation: 'His command is only when He intends a thing that He says to it, "Be," and it is.',
          transliteration: 'Innama amruhu iza arada shay\'an ay-yaqoola lahu kun fayakoon',
        ),
        Verse(
          number: 83,
          arabic: 'فَسُبْحَانَ الَّذِي بِيَدِهِ مَلَكُوتُ كُلِّ شَيْءٍ وَإِلَيْهِ تُرْجَعُونَ',
          translation: 'So exalted is He in whose hand is the realm of all things, and to Him you will be returned.',
          transliteration: 'Fasubhanal-lazee biyadihee malakootu kulli shay\'inw-wa ilayhi turja\'oon',
        ),
      ],
    );
  }
}
